services:
  - type: web
    name: aire-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromEnvVar: MONGO_URI
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: JWT_EXPIRATION
        value: 1h

